"""Dropped name index

Revision ID: 7ecc4160ed28
Revises: d38ec0ffd059
Create Date: 2021-11-09 17:34:48.429581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc4160ed28'
down_revision = 'd38ec0ffd059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    # ### end Alembic commands ###
